version: "2"

services:
  redis:
    image: "bitnami/redis:5.0"
    environment:
      - REDIS_PASSWORD=pw123
    ports:
      - "6379:6379"
    networks:
      - redis_net

  api:
    build:
      context: ./crash-processor-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - redis_net

  consumer:
    build:
      context: ./crash-processor
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - redis_net

volumes:
  redis_data:
    driver: local

networks:
  redis_net:
